### ISSUE TITLE
Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type 

### ISSUE THREAD

**Issue by STiCory** [home-assistant-libs/aiohue#106] opened 2022-02-07 17:17 UTC
Looks like it's related to #102 perhaps, but different?

```
Logger: aiohue.util
Source: /usr/local/share/homeassistant/lib/python3.9/site-packages/aiohue/util.py:175
First occurred: February 6, 2022, 9:40:01 PM (10 occurrences)
Last logged: February 6, 2022, 9:40:01 PM

Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
```

**Comment by marcelveldt** [comment] 2022-02-09 18:44
Yes, duplicate of #102 
I'm working on a solution, needs a small rewrite of the parser. Will be finished soon.

**Closed by marcelveldt** 2022-02-09 18:44 UTC
